config/routes.rb
Adicu::Application.routes.draw do

  resources :authors
  resources :projects
  resources :users
  resources :resources
  resources :features
  resources :posts

  get    'login'  => 'user_session#new',     :as => :login
  post   'login'  => 'user_session#create',  :as => :login
  match 'logout' => 'user_session#destroy', :as => :logout

  match "contact", :to => "home#contact", :as => "contact"
  match "board", :to => "home#board", :as => "board"
  match "jobs", :to => "home#jobs", :as => "jobs"
  match "board_info", :to => "home#board_info", :as => "board_info"

  match "register" => redirect("https://docs.google.com/a/adicu.com/spreadsheet/viewform?formkey=dGd2Qm9iSTBaWFNnS1UwQlUyZ3gwZFE6MQ#gid=0"), :as => :register
  match "blog", :to => "posts#index", :as => "blog"
  match "hackcolumbia" => redirect("http://hackcolumbia.org/"), :as => :hackcolumbia
  match "devfest2011", :to => "home#devfest_2011", :as => "devfest_2011"
  match "devfest", :to => "home#devfest_2013", :as => "devfest"
  match "devfest2012", :to => "home#devfest_2012", :as => "devfest_2012"
  match "devfest2013", :to => "home#devfest_2013", :as => "devfest_2013"
  match "techculture", :to => "home#techculture", :as => "techculture"
  match "jobfair", :to => "home#job_fair_2012", :as => "job_fair_2012"
  match "dinners", :to => "home#dinners", :as => "dinners"
  match "hacksquad", :to => "home#hacksquad", :as => "hacksquad"
  match "math_startup", :to => "home#math_startup", :as => "math_startup"
  match "workshop_resources", :to => "home#workshop_resources", 
	  			:as => "workshop_resources"

  root :to => "home#index"

end

app/views/resources/_form.html.erb
<%= form_for @resource, :html => { :multipart => true } do |f| %>
  <% if @resource.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@resource.errors.count, "error") %> prohibited this resource from being saved:</h2>

      <ul>
      <% @resource.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :url %>
    <%= f.text_field :url %>
  </div>
  <div class="field">
    <%= f.label :entry %><br />
    <%= f.text_area :entry %>
  </div>
  <div class="field">
    <%= f.label :image %><br />
    <%= f.file_field :image %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/resources/_resource.html.erb
<li class="feature">
  <article class="hentry<%= " full" if resource.image.url == "/images/original/missing.png" %>">
  <% puts resource.image.url %>
  <% unless resource.image.url == "/images/original/missing.png" %>
    <figure>
      <%= image_tag resource.image.url(:figure) %>
    </figure>
  <% end %>
    <header>
      <h1 class="entry-title"><%= link_to resource.title, resource.url %></h1>
    </header>
    <div class="entry-content">
      <p><%= resource.entry %></p>
    </div>
  </article>
</li>

app/views/resources/edit.html.erb
<h1>Editing resource</h1>

<%= render 'form' %>

<%= link_to 'Show', @resource %> |
<%= link_to 'Back', resources_path %>

app/views/resources/index.html.erb
<h1>Resources</h1>

<ol id="features">
<%= render :partial => "resource", :collection => @resources %>
</ol>

app/views/resources/new.html.erb
<h1>New resource</h1>

<%= render 'form' %>

<%= link_to 'Back', resources_path %>

app/views/resources/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= @resource.title %>
</p>

<p>
  <b>Url:</b>
  <%= @resource.url %>
</p>

<p>
  <b>Entry:</b>
  <%= @resource.entry %>
</p>


<%= link_to 'Edit', edit_resource_path(@resource) %> |
<%= link_to 'Back', resources_path %>