config/routes.rb
Adicu::Application.routes.draw do

  resources :authors
  resources :projects
  resources :users
  resources :resources
  resources :features
  resources :posts

  get    'login'  => 'user_session#new',     :as => :login
  post   'login'  => 'user_session#create',  :as => :login
  match 'logout' => 'user_session#destroy', :as => :logout

  match "contact", :to => "home#contact", :as => "contact"
  match "board", :to => "home#board", :as => "board"
  match "jobs", :to => "home#jobs", :as => "jobs"
  match "board_info", :to => "home#board_info", :as => "board_info"

  match "register" => redirect("https://docs.google.com/a/adicu.com/spreadsheet/viewform?formkey=dGd2Qm9iSTBaWFNnS1UwQlUyZ3gwZFE6MQ#gid=0"), :as => :register
  match "blog", :to => "posts#index", :as => "blog"
  match "hackcolumbia" => redirect("http://hackcolumbia.org/"), :as => :hackcolumbia
  match "devfest2011", :to => "home#devfest_2011", :as => "devfest_2011"
  match "devfest", :to => "home#devfest_2013", :as => "devfest"
  match "devfest2012", :to => "home#devfest_2012", :as => "devfest_2012"
  match "devfest2013", :to => "home#devfest_2013", :as => "devfest_2013"
  match "techculture", :to => "home#techculture", :as => "techculture"
  match "jobfair", :to => "home#job_fair_2012", :as => "job_fair_2012"
  match "dinners", :to => "home#dinners", :as => "dinners"
  match "hacksquad", :to => "home#hacksquad", :as => "hacksquad"
  match "math_startup", :to => "home#math_startup", :as => "math_startup"
  match "workshop_resources", :to => "home#workshop_resources", 
	  			:as => "workshop_resources"

  root :to => "home#index"

end

app/models/feature.rb
class Feature < ActiveRecord::Base
    has_attached_file :image, :styles => { :figure => "200x200>" }
end

app/controllers/features_controller.rb
class FeaturesController < ApplicationController
  before_filter :require_user, :except => :index

  # GET /features
  # GET /features.xml
  def index
    @features = Feature.order('created_at DESC')

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @features }
    end
  end

  # GET /features/1
  # GET /features/1.xml
  def show
    @feature = Feature.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @feature }
    end
  end

  # GET /features/new
  # GET /features/new.xml
  def new
    @feature = Feature.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @feature }
    end
  end

  # GET /features/1/edit
  def edit
    @feature = Feature.find(params[:id])
  end

  # POST /features
  # POST /features.xml
  def create
    @feature = Feature.new(params[:feature])

    respond_to do |format|
      if @feature.save
        format.html { redirect_to(@feature, :notice => 'Feature was successfully created.') }
        format.xml  { render :xml => @feature, :status => :created, :location => @feature }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @feature.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /features/1
  # PUT /features/1.xml
  def update
    @feature = Feature.find(params[:id])

    respond_to do |format|
      if @feature.update_attributes(params[:feature])
        format.html { redirect_to(@feature, :notice => 'Feature was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @feature.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /features/1
  # DELETE /features/1.xml
  def destroy
    @feature = Feature.find(params[:id])
    @feature.destroy

    respond_to do |format|
      format.html { redirect_to(features_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/features_helper.rb
module FeaturesHelper
end

app/views/features/_feature.html.erb
<li class="feature">
  <article class="hentry<%= " full" if feature.image.url == "/images/original/missing.png" %>">
  <% unless feature.image.url == "/images/original/missing.png" %>
    <figure>
      <%= image_tag feature.image.url(:figure) %>
    </figure>
  <% end %>
    <header>
      <h2 class="entry-category"><%= feature.category %></h2>
      <h1 class="entry-title"><%= link_to feature.title, feature.url %></h1>
    </header>
    <div class="entry-content">
      <p><%= feature.entry %></p>
    </div>
  </article>
</li>

app/views/features/_form.html.erb
<%= form_for @feature, :html => { :multipart => true } do |f| %>

  <% if @feature.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@feature.errors.count, "error") %> prohibited this feature from being saved:</h2>

      <ul>
      <% @feature.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %> 
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :url %> 
    <%= f.text_field :url %>
  </div>
  <div class="field">
    <%= f.label :category %>
    <%= f.text_field :category %>
  </div>
  <div class="field">
    <%= f.label :entry %><br />
    <%= f.text_area :entry %>
  </div>  
  <div class="field">
    <%= f.label :image %><br />
    <%= f.file_field :image %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/features/edit.html.erb
<h1>Editing feature</h1>

<%= render 'form' %>

<%= link_to 'Show', @feature %> |
<%= link_to 'Back', features_path %>

app/views/features/index.html.erb
<ol id="features">
<%= render :partial => "feature", :collection => @features %>
</ol>

app/views/features/new.html.erb
<h1>New feature</h1>

<%= render 'form' %>

<%= link_to 'Back', features_path %>

app/views/features/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= @feature.title %>
</p>

<p>
  <b>Url:</b>
  <%= @feature.url %>
</p>

<p>
  <b>Entry:</b>
  <%= @feature.entry %>
</p>

<p>
  <b>Category:</b>
  <%= @feature.category %>
</p>


<%= link_to 'Edit', edit_feature_path(@feature) %> |
<%= link_to 'Back', features_path %>