config/routes.rb
Adicu::Application.routes.draw do

  resources :authors
  resources :projects
  resources :users
  resources :resources
  resources :features
  resources :posts

  get    'login'  => 'user_session#new',     :as => :login
  post   'login'  => 'user_session#create',  :as => :login
  match 'logout' => 'user_session#destroy', :as => :logout

  match "contact", :to => "home#contact", :as => "contact"
  match "board", :to => "home#board", :as => "board"
  match "jobs", :to => "home#jobs", :as => "jobs"
  match "board_info", :to => "home#board_info", :as => "board_info"

  match "register" => redirect("https://docs.google.com/a/adicu.com/spreadsheet/viewform?formkey=dGd2Qm9iSTBaWFNnS1UwQlUyZ3gwZFE6MQ#gid=0"), :as => :register
  match "blog", :to => "posts#index", :as => "blog"
  match "hackcolumbia" => redirect("http://hackcolumbia.org/"), :as => :hackcolumbia
  match "devfest2011", :to => "home#devfest_2011", :as => "devfest_2011"
  match "devfest", :to => "home#devfest_2013", :as => "devfest"
  match "devfest2012", :to => "home#devfest_2012", :as => "devfest_2012"
  match "devfest2013", :to => "home#devfest_2013", :as => "devfest_2013"
  match "techculture", :to => "home#techculture", :as => "techculture"
  match "jobfair", :to => "home#job_fair_2012", :as => "job_fair_2012"
  match "dinners", :to => "home#dinners", :as => "dinners"
  match "hacksquad", :to => "home#hacksquad", :as => "hacksquad"
  match "math_startup", :to => "home#math_startup", :as => "math_startup"
  match "workshop_resources", :to => "home#workshop_resources", 
	  			:as => "workshop_resources"

  root :to => "home#index"

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= yield(:title) %>Application Development Initiative (ADI)</title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>

<script type='text/javascript'>
  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-18504951-1']);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();

</script>

</head>
<body id="index" class="home">

  <div id="container">

    <nav id="nav">
      <ul>
        <li><%= link_to "Events", Calendar.url %></li>
<!--        <li><%= link_to "Blog", blog_url %></li> -->
	<li><%= link_to "Student Projects", projects_url %></li>
        <li><%= link_to "Board", board_url %></li>
        <li><%= link_to "Contact", contact_url %></li>
        <li><%= link_to "Jobs", jobs_url %></li>
        <% if current_user %>
        <li id="logout"><%= link_to( "Logout", logout_path ) %><li>
        <% end %>
      </ul>
    </nav>

    <header id="banner">
      <h1><%= link_to "Application Development Initiative", "/" %></h1>
      <div id="next_event">
        <%= render :partial => "shared/next_event" %>
      </div>
    </header>

    <section id="content" >
      <%= yield %>
    </section>

    <section id="sidebar" >

      <aside id="getting_started">
        <hgroup>
          <h2>Getting Started</h2>
          <p>See what the ADI has to offer you, an aspiring student developer at Columbia, by checking out the following resources:</p>
        </hgroup>
        <ul>
          <li><a target="_blank" href="http://eepurl.com/jaugD">Mailing List</a></li>
          <li><a target="_blank" href="<%= Calendar.url %>">Events</a></li>
          <li><a target="_blank" href="http://wiki.adicu.com/">Wiki</a></li>
        </ul>
      </aside>

      <aside id="about_us">
        <h2>About Us</h2>
        <p>The primary goal of the Application Development Initiative is to nurture student creativity and technological aptitude by creating a communal resource for developers of all talents and interests.</p>
        <p>Columbia University students of all backgrounds are invited and encouraged to take an active role in this initiative.</p>
        <p id="social_links">
          <a href="http://facebook.com/adicu"><%= image_tag( "fb.png" ) %></a>
          <a href="http://gplus.to/adicu"><%= image_tag( "googleplus.png" ) %></a>
          <a href="http://twitter.com/adicu"><%= image_tag( "twitter_new.png" ) %></a>
          <a href="http://github.com/adicu/"><%= image_tag( "github.png" ) %></a>
        </p>
      </aside>

    </section>

    <footer id="contentinfo" >
      <p id="licensing-info">
        <a rel="license" href="http://creativecommons.org/licenses/by-nc-sa/3.0/"><img alt="Creative Commons License" style="border-width:0" src="http://i.creativecommons.org/l/by-nc-sa/3.0/88x31.png" /></a>
        This work is licensed under a <a rel="license" href="http://creativecommons.org/licenses/by-nc-sa/3.0/">Creative Commons license</a>.
        <span class="logo-small"><%= Time.now.year %></p>
    </footer>

  </div>

</body>
</html>